// AUTO-GENERATED by @davidoost/eva-nextjs-sdk generate — do not edit manually.
import { createBrowserClient } from '@davidoost/eva-nextjs-sdk/client';
import { SERVICE_MAP } from './generated/service-map';
import type { GeneratedMethods } from './generated/service-map';

export const createClient = (token?: string, options?: { baseUrl?: string; namespace?: string }) =>
  createBrowserClient<GeneratedMethods>({
    baseUrl: options?.baseUrl ?? process.env.NEXT_PUBLIC_EVA_BASE_URL!,
    namespace: options?.namespace,
    serviceMap: SERVICE_MAP,
    token,
  });
