// AUTO-GENERATED by @davidoost/eva-nextjs-sdk generate — do not edit manually.
import {
  createServerClient,
  createApiClient as createApiClientBase,
} from "@davidoost/eva-nextjs-sdk/server";
import { cookies } from "next/headers";
import { SERVICE_MAP } from "./generated/service-map";
import type { GeneratedMethods } from "./generated/service-map";

export async function createClient(options?: {
  baseUrl?: string;
  namespace?: string;
}) {
  const cookieStore = await cookies();
  return createServerClient<GeneratedMethods>({
    serviceMap: SERVICE_MAP,
    baseUrl: options?.baseUrl,
    namespace: options?.namespace,
    cookies: {
      getAll() {
        return cookieStore.getAll();
      },
      setAll(cookiesToSet) {
        try {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options),
          );
        } catch {}
        // Server Components cannot write cookies — middleware handles it.
      },
    },
  });
}

export const createApiClient = (options?: { baseUrl?: string }) =>
  createApiClientBase<GeneratedMethods>({
    serviceMap: SERVICE_MAP,
    baseUrl: options?.baseUrl,
  });
