import type { Metadata } from "next";
import { Geist, Young_Serif } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
  display: "swap",
});

const youngSerif = Young_Serif({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "EVA PIM",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`bg-background ${geist.variable} ${youngSerif.variable} ${geist.className}`}
    >
      <body className="flex w-full min-h-dvh justify-center font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
